project:
  type: website
  title: "AI MarTech Development Principles"
  output-dir: "_site"

website:
  title: "AI MarTech Principles"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Meta Principles (MP)"
        menu:
          - text: "Axiomatization System"
            href: principles_qmd/MP000_axiomatization_system.qmd
          - text: "Don't Repeat Yourself"
            href: principles_qmd/MP018_dont_repeat_yourself.qmd
          - text: "Functor-Module Correspondence"
            href: principles_qmd/MP044_functor_module_correspondence.qmd
      - text: "Principles (P)"
        menu:
          - text: "App Construction"
            href: principles_qmd/P004_app_construction_principles.qmd
      - text: "Rules (R)"
        menu:
          - text: "Functional Encapsulation"
            href: principles_qmd/R067_functional_encapsulation.qmd
          - text: "One Function One File"
            href: principles_qmd/R021_one_function_one_file.qmd
          - text: "Standard Path Constants"
            href: principles_qmd/R114_standard_path_constants.qmd
      - text: "Data Flow (DF)"
        menu:
          - text: "Pipeline Architecture"
            href: principles_qmd/DF00_pipeline_architecture.qmd
          - text: "Staging Operations"
            href: principles_qmd/DF01_staging_operations.qmd
          - text: "Transformation Operations"
            href: principles_qmd/DF02_transformation_operations.qmd
          - text: "Cleansing Operations"
            href: principles_qmd/DF03_cleansing_operations.qmd
          - text: "Processing Operations"
            href: principles_qmd/DF04_processing_operations.qmd
          - text: "Application Data"
            href: principles_qmd/DF05_application_data.qmd
      - text: "ETL Operations"
        menu:
          - text: "ETL Framework"
            href: principles_qmd/ETL00_framework.qmd
          - text: "Customer DNA Analysis"
            href: principles_qmd/ETL01_extract.qmd
          - text: "Customer View Filtering"
            href: principles_qmd/ETL02_transform.qmd
          - text: "product Profiles Import"
            href: principles_qmd/ETL03_product_profiles.qmd
          - text: "Extensible Framework"
            href: principles_qmd/ETL04_extensible.qmd
      - text: "Templates (T)"
        menu:
          - text: "Template Overview"
            href: principles_qmd/T00_template_overview.qmd
          - text: "Update Scripts"
            href: principles_qmd/T01_update_scripts.qmd
          - text: "Component Structure"
            href: principles_qmd/T02_components.qmd
          - text: "ETL Pipelines"
            href: principles_qmd/T03_etl_pipelines.qmd
          - text: "Path Migration Summary"
            href: principles_qmd/T04_path_migration_summary.qmd
          - text: "ETL Initialization"
            href: principles_qmd/T05_etl_initialization.qmd
      - text: "Derivations (D)"
        menu:
          - text: "Data Processing Overview"
            href: principles_qmd/D00_data_processing_overview.qmd
          - text: "DNA Analysis"
            href: principles_qmd/D01_dna_analysis.qmd
          - text: "Customer View Filtering"
            href: principles_qmd/D02_customer_filtering.qmd
    right:
      - icon: github
        href: https://github.com/your-repo
        text: "Source"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Meta Principles (MP)"
        contents:
          - principles_qmd/MP000_axiomatization_system.qmd
          - principles_qmd/MP018_dont_repeat_yourself.qmd
          - principles_qmd/MP044_functor_module_correspondence.qmd
      - section: "Principles (P)"
        contents:
          - principles_qmd/P004_app_construction_principles.qmd
      - section: "Rules (R)"
        contents:
          - principles_qmd/R021_one_function_one_file.qmd
          - principles_qmd/R067_functional_encapsulation.qmd
          - principles_qmd/R114_standard_path_constants.qmd
      - section: "Data Flow (DF)"
        contents:
          - principles_qmd/DF00_pipeline_architecture.qmd
          - principles_qmd/DF01_staging_operations.qmd
          - principles_qmd/DF02_transformation_operations.qmd
          - principles_qmd/DF03_cleansing_operations.qmd
          - principles_qmd/DF04_processing_operations.qmd
          - principles_qmd/DF05_application_data.qmd
      - section: "ETL Operations"
        contents:
          - principles_qmd/ETL00_framework.qmd
          - principles_qmd/ETL01_extract.qmd
          - principles_qmd/ETL02_transform.qmd
          - principles_qmd/ETL03_product_profiles.qmd
          - principles_qmd/ETL04_extensible.qmd
      - section: "Templates (T)"
        contents:
          - principles_qmd/T00_template_overview.qmd
          - principles_qmd/T01_update_scripts.qmd
          - principles_qmd/T02_components.qmd
          - principles_qmd/T03_etl_pipelines.qmd
          - principles_qmd/T04_path_migration_summary.qmd
          - principles_qmd/T05_etl_initialization.qmd
      - section: "Derivations (D)"
        contents:
          - principles_qmd/D00_data_processing_overview.qmd
          - principles_qmd/D01_dna_analysis.qmd
          - principles_qmd/D02_customer_filtering.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: show
    code-tools: true
    highlight-style: github
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    crossrefs-hover: true

execute:
  echo: true
  eval: false
  warning: false
  message: false

bibliography: references.bib
csl: apa.csl

filters:
  - quarto