# Parameters for the precision marketing system
# This file defines system-wide parameters including the list of company models

# Companies list in standard YAML format
companies:
  - KitchenMAMA
  - WISER
  - MAMBA

# Legacy format (kept for backward compatibility)
COMPANY_LIST: KitchenMAMA
COMPANY_LIST: WISER
COMPANY_LIST: MAMBA

# Model theory parameters
model_theory:
  axiom_files:
    - MP00_axiomatization_system.md
    - MP01_primitive_terms_and_definitions.md
  
  # Interpretation function maps model elements to their meanings
  interpretation_function:
    domain: "companies"
    codomain: "implementation_specifics"

# System paths
system:
  base_path: "$HOME/Library/CloudStorage/Dropbox/precision_marketing"
  repository_pattern: "precision_marketing_{company}/precision_marketing_app"
  global_scripts_path: "update_scripts/global_scripts"

# Global synchronization settings
synchronization:
  auto_sync: true
  sync_check_interval: 86400  # 24 hours in seconds
  conflict_resolution: "manual"  # Options: manual, auto-merge, prefer-local, prefer-remote

# Component n-tuple pattern configuration
component_ntuple:
  # Core aspects of the component pattern
  core_aspects:
    - name: "UI"
      suffix: "UI"
      description: "Visual presentation and structure"
      required: true
    - name: "FilterUI"
      suffix: "FilterUI"
      description: "Component-specific filtering interface"
      required: false
    - name: "Server"
      suffix: "Server"
      description: "Business logic and data processing"
      required: true
    - name: "Defaults"
      suffix: "Defaults"
      description: "Default values for all UI outputs"
      required: true
    - name: "Initialize"
      suffix: "Initialize"
      description: "Integration function connecting all components"
      required: false